/* DDL - Data Definition Lenguage */
    -- CREATE TABLE <Table_Name> (C1 TYPE, C2 TYPE, ... , Cn TYPE)
CREATE TABLE test (
    code NUMBER,
    name VARCHAR2(100)
);

CREATE TABLE test2 (
    code NUMBER DEFAULT 0,
    name VARCHAR2(100) DEFAULT 'John Doe',
    date_in DATE DEFAULT SYSDATE
);

        -- CREATE TABLE FROM OTHER TABLES
CREATE TABLE empleados AS SELECT * FROM employees;
CREATE TABLE empleados2 AS SELECT * FROM employees WHERE department_id > 50;
CREATE TABLE empleados3 AS SELECT * FROM employees WHERE department_id > 50;
CREATE TABLE empleados4 AS SELECT first_name || ' ' || last_name AS "Nombre", salary as "Salario", salary*12 AS "Salario Anual" FROM employees;

        --> CONSTRAINTS (NOT NULL, UNIQUE, PRIMARY KEY, FOREIGN KEY, CHECK)
CREATE TABLE test3 (
    code NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);
        --// TABLE CONSTRAINT
CREATE TABLE test4 (
    code1 NUMBER,
    code2 NUMBER,
    name VARCHAR2(100),
    PRIMARY KEY (code1, code2)
);
        --// UNIQUE
CREATE TABLE test5 (
    code NUMBER PRIMARY KEY,
    name VARCHAR2(100) UNIQUE
);
        --// CONSTRAINT NAMING
CREATE TABLE test6 (
    code NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    CONSTRAINT Name_I UNIQUE(name)
);

        -- exercises
CREATE TABLE student (
    COD_REGISTRY NUMBER,
    NAME VARCHAR2(20 BYTE),
    SURNAME VARCHAR2(20 BYTE),
    LASTNAME VARCHAR2(20 BYTE),
    AGE NUMBER,
    DATE_REGISTRY DATE
);
DESC student;

CREATE TABLE centros(
    CODIGO_CENTRO NUMBER,
    NOMBRE VARCHAR2(100),
    PROVINCIA VARCHAR2(100) DEFAULT 'MADRID',
    FECHA_ALTA DATE DEFAULT SYSDATE,
    NUM_ALUMNOS NUMBER DEFAULT 0
);
DESC centros;
INSERT INTO CENTROS (CODIGO_CENTRO, NOMBRE) VALUES(1,'MATEMÁTICAS');
SELECT * FROM CENTROS;

CREATE TABLE cursos(
    COD_CURSO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL UNIQUE,
    RESPONSABLE VARCHAR2(100)
);
DESC cursos;
INSERT INTO cursos VALUES(1,'Python Fundamentals', 'John Doe');
INSERT INTO cursos VALUES(3,'Algorithms', 'Jane Smith');    


        --// FOREIGN  KEY
CREATE TABLE CURSOS(
    COIGO NUMBER PRIMARY KEY, ---> PK
    NOMBRE VARCHAR2(100) NOT NULL UNIQUE,
    RESPONSABLE VARCHAR2(100)
);
CREATE TABLE ALUMNOS(
    COD_ALUMNO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100),
    COD_CURSO NUMBER REFERENCES CURSOS(CODIGO) ---> FK
);
INSERT INTO CURSOS(CODIGO, NOMBRE) VALUES(3, 'WEB');
INSERT INTO ALUMNOS VALUES(100, 'RAUL', 'PEREZ', 1);
        --// FOREIGN KEY AT TABLE LEVEL
            --** CONTRAINT <REFERENCED_TABLE_CURRENT_TABLE> FOREIGN KEY (<UNIQUE_COLUMN>) REFERENCES(<PK_REFERENCED_TABLE>)
CREATE TABLE ALUMNOS2(
    COD_ALUMNO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100),
    COD_CURSO NUMBER,
    CONSTRAINT CURSO_ALUMNO FOREIGN KEY(COD_CURSO) REFERENCES CURSOS(CODIGO) --> FK
);


        --// CHECK CONSTRAINT
CREATE TABLE employee(
    code NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    salary NUMBER CHECK(salary > 1000)
);
INSERT INTO employee VALUES(1, 'John Doe' ,900);

CREATE TABLE employee2(
    code NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL CHECK(name = UPPER(name)),
    salary NUMBER CHECK(salary > 1000)
);
INSERT INTO employee2 VALUES(1, 'JOHN DOE' ,1100);


    -- ALTER TABLE
        --> ADD COLUMN
ALTER TABLE CURSOS ADD(
    PROFESOR VARCHAR2(100),
    TUTOR VARCHAR2(100)
);

        --> UPDATE COLUMN
ALTER TABLE cursos MODIFY (profesor VARCHAR2(50));
ALTER TABLE cursos MODIFY (profesor NUMBER);

        --> DEFAULT VALUE
ALTER TABLE cursos MODIFY (tutor VARCHAR2(100) DEFAULT 'Tutor1');

        --> DELETE ONE COLUMN
 ALTER TABLE cursos DROP(tutor);

        --> READ ONLY / READ WRITE
ALTER TABLE cursos READ ONLY;
ALTER TABLE cursos READ WRITE;

INSERT INTO cursos VALUES (4, 'John', NULL, NULL);

    
    
    -- DROP TABLE <Table_Name>
DROP TABLE cursos CASCADE CONSTRAINTS;
DROP TABLE alumnos2;





-- Exercises
CREATE TABLE paises(
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL CHECK(nombre = UPPER(nombre))
);

DROP TABLE ciudades;
CREATE TABLE ciudades(
    cod_ciudad NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL CHECK(nombre = UPPER(nombre)),
    poblacion NUMBER NOT NULL CHECK (poblacion > 0),
    cod_pais NUMBER REFERENCES paises(codigo)
);

INSERT INTO paises VALUES(28, 'ESTADOS UNIDOS');
INSERT INTO paises VALUES(29, 'FRANCIA');
INSERT INTO ciudades VALUES(1, 'NUEVA YORK', 4000000, 28);
INSERT INTO ciudades VALUES(2, 'ROMA', 3000000, 40);
INSERT INTO paises VALUES(40, 'ITALIA');
INSERT INTO ciudades VALUES(4, 'CALIFORNIA', 3000000, 28);
INSERT INTO ciudades VALUES(5, 'PARIS', 4000000, 29);
INSERT INTO ciudades VALUES(6, 'FLORIDA', 4500000, 28);
CREATE TABLE ciudades_peque AS SELECT * FROM ciudades WHERE poblacion < 2000000;
ALTER TABLE ciudades_peque ADD (codigo NUMBER PRIMARY KEY);
ALTER TABLE ciudades_peque ADD (bandera VARCHAR2(100));
DROP TABLE ciudades_peque;









