/* PARTITIONED TABLES */
-- INSERTS OVER THE MAX VALUE IN PARTITIONS ARE NOT ALLOWED
-- IT IS NOT ALLOWED TO CREATE PARTITIONS BETWEEN VALUES OF TWO PARTITIONS ALREADY CREATED
    /* 
    PARTITION BY RANGE (<COLUMN_1>, ... ,  <COLUMN_n>) {
        PARTITION P1 VALUES LESS THAN (<VALUE_1>),
        PARTITION P2 VALUES LESS THAN (<VALUE_2>),
        PARTITION Pn VALUES LESS THAN (<VALUE_n>),
        PARTITION Pm VALUES LESS THAN (MAXVALUE)
    }
    */
CREATE TABLE range(
    code NUMBER NOT NULL,
    data VARCHAR2(100)
)
    PARTITION BY RANGE(code) (
        PARTITION P1 VALUES LESS THAN (10),
        PARTITION P2 VALUES LESS THAN (20),
        PARTITION P3 VALUES LESS THAN (30),
        PARTITION P4 VALUES LESS THAN (40)
    );

SELECT * FROM USER_PART_TABLES;
SELECT * FROM USER_TAB_PARTITIONS  WHERE TABLE_NAME = 'RANGE';
    
    -- INSERT INTO PARTITIONS
INSERT INTO range VALUES(21, 'aaa');
INSERT INTO range VALUES(8, 'bbb');
SELECT * FROM range;
SELECT * FROM range PARTITION(p3);
SELECT * FROM range PARTITION(p1);
SELECT * FROM range WHERE code = 21;
SELECT * FROM range WHERE code > 21;

    -- ADD PARTITIONS
ALTER TABLE range ADD PARTITION P5 VALUES LESS THAN (50);
SELECT * FROM USER_TAB_PARTITIONS  WHERE TABLE_NAME = 'RANGE';
INSERT INTO range VALUES(40, 'ccc');
SELECT * FROM range PARTITION(p5);
ALTER TABLE range ADD PARTITION P6 VALUES LESS THAN (100);

    -- MAXVALUE = Infinite
ALTER TABLE range ADD PARTITION P7 VALUES LESS THAN (MAXVALUE);
INSERT INTO range VALUES(400, 'ddd');

ALTER TABLE range ADD PARTITION P7 VALUES LESS THAN (100); --> Not allowed


    -- UPDATE WITH PARTITION MOVEMENT
ALTER TABLE range ENABLE ROW MOVEMENT; --> leads to loss of performance, so not recommended
SELECT * FROM range;
UPDATE range SET code = 29 WHERE code = 30;

    -- MERGE RANGE PARTITIONS
SELECT * FROM USER_TAB_PARTITIONS  WHERE TABLE_NAME = 'RANGE';
        --Only adjacent partitions can be merged
ALTER TABLE range MERGE PARTITIONS p3,p4 INTO PARTITION p3_4;
ALTER TABLE range MERGE PARTITIONS p1,p7 INTO PARTITION p1_7; --> NOT ALLOWED
        -- MULTIPLE PARTITIONS
ALTER TABLE range MERGE PARTITIONS p5 TO p7 INTO PARTITION p5_6_7;


    
    -- PARTITIONS BY LISTS
    /* 
    PARTITION BY LIST (<COLUMN_1>, ... ,  <COLUMN_n>) {
        PARTITION P1 VALUES (<VALUE_1>, <VALUE_2>),
        PARTITION P2 VALUES (<VALUE_3>, <VALUE_4>),
        PARTITION Pn VALUES (<VALUE_5>, <VALUE_6>, <VALUE_7>),
        PARTITION Pm VALUES (DEFAULT)
    }
    */

CREATE TABLE lista
(
    Codigo NUMBER NOT NULL,
    Pais VARCHAR2(100),
    Cliente VARCHAR2(100)
)
    PARTITION BY LIST (pais)
    (
        PARTITION Europa VALUES ('España', 'Francia', 'Alemania'),
        PARTITION Latinoamerica VALUES ('Argentina', 'Chile'),
        PARTITION Asia VALUES ('Malasia', 'China', 'Indonesia')
    );

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'LISTA';
INSERT INTO lista VALUES (1, 'Francia', 'Cliente1');
SELECT * FROM lista PARTITION (EUROPA);
ALTER TABLE lista ENABLE ROW MOVEMENT;
UPDATE lista SET pais = 'China' WHERE pais='Francia';

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'LISTA';
INSERT INTO lista VALUES (2, 'USA', 'Cliente2');
ALTER TABLE lista ADD PARTITION VALUES ('USA', 'Canada'); --> If no name is provided oracle put generic names like SYS_P702
ALTER TABLE lista RENAME PARTITION SYS_P702 TO NorteAmerica;
SELECT * FROM lista;
SELECT * FROM lista PARTITION(NORTEAMERICA);

    -- DEFAULT
ALTER TABLE lista ADD PARTITION otros VALUES (DEFAULT);
INSERT INTO lista VALUES (3, 'Australia', 'Cliente3');
SELECT * FROM lista PARTITION(otros);

    -- MERGE LIST PARTITIONS
ALTER TABLE lista MERGE PARTITIONS latinoamerica, norteamerica INTO PARTITION america;


    -- PARTITIONS BY HASH
    -- MERGE IS NOT ALLOWED WITH HASH PARTITIONS
    /*
    PARTITION BY HASH(<COL_1>, ... , <COL_n>)
    PATITIONS m
    */
CREATE TABLE hash_table
(
    code NUMBER NOT NULL,
    data VARCHAR2(100)
)
    PARTITION BY HASH (code)
    PARTITIONS 3;
    
SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME='HASH_TABLE';
    
    

    -- DELETE PARTITIONS
SELECT * FROM USER_TAB_PARTITIONS;
ALTER TABLE range DROP PARTITION p3_4;



    -- SUBPARTITIONS: RANGE-HASH
CREATE TABLE rango_sub
(
    codigo NUMBER NOT NULL,
    datos VARCHAR2(100),
    fecha DATE,
    cod_cliente NUMBER
)
    PARTITION BY RANGE(fecha)
        SUBPARTITION BY HASH (cod_cliente) SUBPARTITIONS 3
        (
            PARTITION trimestre1 VALUES LESS THAN (TO_DATE('01-04-2023','dd-mm-yyyy')),
            PARTITION trimestre2 VALUES LESS THAN (TO_DATE('01-07-2023','dd-mm-yyyy')),
            PARTITION trimestre3 VALUES LESS THAN (TO_DATE('01-10-2023','dd-mm-yyyy')),
            PARTITION trimestre4 VALUES LESS THAN (TO_DATE('01-01-2024','dd-mm-yyyy'))
        );
        
SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'RANGO_SUB'; -- Login partitions, no data in here
SELECT * FROM USER_TAB_SUBPARTITIONS WHERE TABLE_NAME = 'RANGO_SUB'; -- Here goes the data


    -- SUBPARTITIONS: RANGE-LIST
CREATE TABLE RANGO_LISTA
(	
    CODIGO NUMBER NOT NULL , 
	DATOS VARCHAR2(100)	,
    FECHA date,
    PAIS VARCHAR2(50)
)
  PARTITION BY RANGE (FECHA)
     SUBPARTITION BY LIST(PAIS) 
    (
        PARTITION TRIMESTRE1 VALUES LESS THAN (TO_DATE('01-04-2023','dd-mm-yyyy'))
        ( 
          SUBPARTITION T1_P1 VALUES('ESPAÑA','FRANCIA','ALEMANIA'),
          SUBPARTITION T1_P2 VALUES('ARGENTINA','CHILE'),
          SUBPARTITION T1_P3 VALUES('USA','CANADA'),
          SUBPARTITION T1_P4 VALUES(DEFAULT)
        ),
        PARTITION TRIMESTRE2 VALUES LESS THAN (TO_DATE('01-07-2023','dd-mm-yyyy'))
        ( 
          SUBPARTITION T2_P1 VALUES('ESPAÑA','FRANCIA','ALEMANIA'),
          SUBPARTITION T2_P2 VALUES('ARGENTINA','CHILE'),
          SUBPARTITION T2_P3 VALUES('USA','CANADA'),
          SUBPARTITION T2_P4 VALUES(DEFAULT)
        ),
        PARTITION TRIMESTRE3 VALUES LESS THAN (TO_DATE('01-10-2023','dd-mm-yyyy'))
        ( 
          SUBPARTITION T3_P1 VALUES('ESPAÑA','FRANCIA','ALEMANIA'),
          SUBPARTITION T3_P2 VALUES('ARGENTINA','CHILE'),
          SUBPARTITION T3_P3 VALUES('USA','CANADA'),
          SUBPARTITION T3_P4 VALUES(DEFAULT)
        ),
        PARTITION TRIMESTRE4 VALUES LESS THAN (TO_DATE('01-01-2024','dd-mm-yyyy'))
        ( 
          SUBPARTITION T4_P1 VALUES('ESPAÑA','FRANCIA','ALEMANIA'),
          SUBPARTITION T4_P2 VALUES('ARGENTINA','CHILE'),
          SUBPARTITION T4_P3 VALUES('USA','CANADA'),
          SUBPARTITION T4_P4 VALUES(DEFAULT)
        )
    );


select * from user_tab_partitions where table_name='RANGO_LISTA'; -- Logic partitions, no data here
select * from user_tab_subpartitions where table_name='RANGO_LISTA'; -- Data remains in subpartitions


INSERT INTO RANGO_LISTA VALUES(1,'AAAA', TO_DATE('02-04-2023', 'dd-mm-yyyy'), 'USA');
INSERT INTO RANGO_LISTA VALUES(2,'BBBB', TO_DATE('06-05-2023','dd-mm-yyyy'),'CHILE');
SELECT * FROM RANGO_LISTA;
SELECT * FROM RANGO_LISTA PARTITION(TRIMESTRE2);
SELECT * FROM RANGO_LISTA SUBPARTITION(T2_P2);
SELECT * FROM RANGO_LISTA SUBPARTITION(T2_P3);





