/* SELECT */
SELECT FIRST_NAME, PHONE_NUMBER FROM EMPLOYEES;
SELECT FIRST_NAME AS NOMBRE, JOB_ID AS "Tipo de Trabajo" FROM EMPLOYEES;
SELECT * FROM REGIONS;
SELECT COUNTRY_NAME FROM COUNTRIES;
select street_address as "Dirección", city as "Ciudad", state_province as "Estado" from locations;


/* OPERATORS (+, -, *, /, %) */
SELECT FIRST_NAME, SALARY as "Bruto", SALARY *20/100 AS "Impuestos", salary-(salary*20/100) as "Neto" FROM EMPLOYEES;
select first_name as "Nombre", salary as "Salario", salary*14 as "Salario Anual" from employees;


/* LITERALS */
SELECT 'NAME:' || FIRST_NAME FROM EMPLOYEES;
SELECT 'NAME:' || FIRST_NAME || ' ' || LAST_NAME AS "Name Employee" FROM EMPLOYEES;
SELECT 'El empleado ' || FIRST_NAME || ' del departamento ' || DEPARTMENT_ID || ' tiene un salario de $' || SALARY AS "Employee Info"  FROM EMPLOYEES;
SELECT 'The street ' || STREET_ADDRESS || ' belongs to the city of ' || CITY AS "Street Info" FROM LOCATIONS;


/* DUAL TABLE */
SELECT 4+3, FIRST_NAME FROM EMPLOYEES;
SELECT 4+3 FROM DUAL;
DESC DUAL;


/* NULLS */
    -- Operations with nulls equals null 
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, SALARY * COMMISSION_PCT AS "Total Salary" FROM EMPLOYEES;


/* DISTINCTS */
SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;
SELECT * FROM LOCATIONS;
SELECT DISTINCT CITY FROM LOCATIONS;
SELECT DISTINCT JOB_ID, DEPARTMENT_ID FROM EMPLOYEES;


/* WHERE */
    -- SELECT <DATA> FROM <TABLE> WHERE <CONDITION>
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 100;
SELECT * FROM COUNTRIES WHERE REGION_ID = 3;

    -- COMPARISON OPERATORS ( =, >, <, >=, <=, <> ) 
SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > 5000;
SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID <> 50;
SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE MANAGER_ID <> 114;


/* LITERAL CONDITIONS */
    -- literals are case sensitive
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME='John';
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME='john';
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME<>'John';
SELECT * FROM EMPLOYEES WHERE LAST_NAME <> 'Smith';
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'ST_CLERK';
SELECT CITY, STREET_ADDRESS FROM LOCATIONS WHERE COUNTRY_ID='US';


/* DATE COMPARISON */
    -- JULIAN NUMBER = 01/01/4712 AC
SELECT * FROM EMPLOYEES ;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE='21/JUN/2007';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE>'21/JUN/2007';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE<'21/JUN/2007';
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE HIRE_DATE >= '01/JAN/2006';


/* BETWEEN */
    -- BETWEEN <VALUE1> AND <VALUE2>
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 6000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '01-JAN-07' AND '01-JAN-09';
SELECT * FROM EMPLOYEES WHERE  first_name BETWEEN 'Douglas' AND 'Steven';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID BETWEEN 40 AND 60;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '01/JAN/2002' AND '01/JAN/2004';
SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME BETWEEN 'D' AND 'G';


/* IN CLAUSE */
    -- IN (<VALUE_1>, <VALUE_2>, <VALUE_N>)
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (50,60);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('SH_CLERK', 'ST_CLERK', 'ST_MAN');
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (30, 60, 90);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'PU_CLERK');
SELECT CITY FROM LOCATIONS WHERE COUNTRY_ID IN ('UK', 'JP');


/* LIKE CLAUSE */
    -- LIKE <PATTERN>
    -- '%' ANY SECUENCE
    -- '_' ONLY ONE CHARACTER
SELECT first_name FROM EMPLOYEES WHERE first_name LIKE 'J%';
SELECT * FROM employees WHERE first_name LIKE '_e%';
SELECT * FROM employees WHERE first_name LIKE '%te%';
SELECT * FROM employees WHERE first_name LIKE 'J%';
SELECT * FROM employees WHERE first_name LIKE 'S%n';
SELECT * FROM countries;
SELECT COUNTRY_NAME FROM COUNTRIES WHERE COUNTRY_NAME LIKE '_r%';


/* IS NULL CLAUSE */
SELECT * FROM employees WHERE commission_pct = NULL;
SELECT * FROM employees WHERE commission_pct IS NULL;
SELECT * FROM employees WHERE commission_pct IS NOT NULL;
SELECT CITY FROM LOCATIONS WHERE STATE_PROVINCE IS NULL;
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, SALARY*(1+COMMISSION_PCT) AS "Total Income"  FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

/* <CONDITION_1> <CONDITION_2> */
    -- AND TRUE TRUE --> TRUE
    -- AND TRUE FALSE --> FALSE
    -- OR TRUE FALSE --> TRUE
    -- OR TRUE TURE --> TRUE

/* 'AND', 'OR', 'NOT' */
    -- <CONDITION_1> AND <CONDITION_2>
    -- <CONDITION_1> OR <CONDITION_2>
    -- NOT <CONDITION_1>
SELECT * FROM employees WHERE salary > 5000 AND department_id = 50;
SELECT * FROM employees WHERE salary > 5000 OR department_id = 50;
SELECT * FROM employees WHERE department_id NOT IN (50, 60);

/* MULTIPLE CONDITIONS */
    -- <C1> OR <C2> AND <C3> --> <C1> OR <C2> --> <R1> AND <C3>  --> <R2>
    -- TRUE    TRUE    FALSE -->     ...     --> TRUE AND FALSE --> FALSE
/*
<C1> AND <C2> OR <C3>
 F        T        T --> TRUE

<C1> AND (<C2> OR <C3>)
 F         T        T --> FALSE
*/    
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE FROM EMPLOYEES WHERE SALARY > 5000 AND DEPARTMENT_ID = 50 AND HIRE_DATE > '01/JAN/05';
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE FROM EMPLOYEES WHERE SALARY > 5000 AND DEPARTMENT_ID = 50 OR HIRE_DATE > '01/JAN/05';
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE FROM EMPLOYEES WHERE SALARY > 5000 AND (DEPARTMENT_ID = 50 OR HIRE_DATE > '01/JAN/05');
SELECT FIRST_NAME, HIRE_DATE, JOB_ID FROM EMPLOYEES WHERE JOB_ID='IT_PROG' AND SALARY < 6000;
SELECT * FROM employees WHERE department_id IN (50, 80) AND first_name LIKE 'S%' AND salary > 3000;
SELECT * FROM employees WHERE job_id='IT_PROG' AND PHONE_NUMBER LIKE '5%' AND hire_date BETWEEN '01/JAN/07' AND '31/DEC/07';


/* ORDER BY CLASUE */
    -- SELECT <DATA> FROM <TABLE> ORDER BY <DATA> DESC/ASC;
SELECT * FROM employees ORDER BY first_name;
SELECT * FROM employees ORDER BY first_name, last_name;
SELECT first_name, last_name, salary FROM employees WHERE first_name='David' ORDER BY first_name, last_name;
SELECT first_name, last_name, salary FROM employees WHERE first_name='David' ORDER BY salary DESC;
SELECT first_name, salary*12 FROM employees ORDER BY salary*12;

    -- Order by position [2]
SELECT first_name, salary*12 FROM employees ORDER BY 2; 

    -- Order by alias
SELECT first_name, salary*12 AS Total FROM employees ORDER BY Total DESC; 


/* FETCH CLAUSE */
SELECT FIRST_NAME, SALARY FROM employees ORDER BY salary DESC FETCH FIRST 5 ROWS ONLY;
SELECT FIRST_NAME, SALARY FROM employees ORDER BY salary DESC FETCH FIRST 7 ROWS WITH TIES;
SELECT FIRST_NAME, SALARY FROM employees ORDER BY salary DESC OFFSET 5 ROWS FETCH FIRST 7 ROWS ONLY;
SELECT * FROM employees FETCH FIRST 20 PERCENT ROWS ONLY;
SELECT * FROM employees FETCH FIRST 20 PERCENT ROWS WITH TIES;









