/* SEQUENCES */
CREATE SEQUENCE seq1 INCREMENT BY 1 MAXVALUE 1000 MINVALUE 20 CACHE 20;
    
    -- NEXT VALUE
SELECT seq1.NEXTVAL FROM DUAL;

    -- CURRENT VALUE
SELECT seq1.CURRVAL FROM DUAL;

    -- USE
INSERT INTO regions VALUES(seq1.NEXTVAL, 'ZZZZZ');

    -- DROP
DROP SEQUENCE seq1;


-- Exercises
CREATE SEQUENCE seq2 INCREMENT BY 5 MINVALUE 1;
SELECT * FROM paises;
INSERT INTO paises VALUES(seq2.NEXTVAL, 'MEXICO');
INSERT INTO paises VALUES(seq2.NEXTVAL, 'BRASIL');




